Create CODE_OF_CONDUCT.md
c0sm0void/ReVot pull request #15
Opened 2024-10-02 13:46 UTC by tharun634

Resolves #14

2024-10-02 15:38 UTC, whyvineet requested changes
This code of conduct appears to be directly copied from the Contributor Covenant. While the Contributor Covenant is a great resource, it's important to create a Code of Conduct tailored to ReVot's specific needs and values.

Reference the Contributor Covenant as a starting point, but customize it with ReVot's values and expectations.

2024-10-02 16:28 UTC, tharun634 commented
> tailored to ReVot's specific needs and values.

> customize it with ReVot's values and expectations.

Anywhere I can refer to understand ReVot's values and expectations? From what I see, the README only gives a brief about the project and steps to use it

2024-10-02 16:59 UTC, whyvineet commented
> > tailored to ReVot's specific needs and values.
> 
> > customize it with ReVot's values and expectations.
> 
> Anywhere I can refer to understand ReVot's values and expectations? From what I see, the README only gives a brief about the project and steps to use it

All the values and expectations are mentioned in your `CODE_OF_CONDUCT.md` file! I mean to say, make change like:

### You can use:
We as members, contributors, and leaders pledge to make participation in the `ReVot` community a harassment-free experience for everyone, regardless of age, body size, visible or invisible disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation.

### Instead of:
We as members, contributors, and leaders pledge to make participation in our community a harassment-free experience for everyone, regardless of age, body size, visible or invisible disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation.

### Similarly,
We pledge to act and interact in ways that contribute to an open, welcoming, diverse, inclusive, and healthy community within the `ReVot` ecosystem.

### Rather than
We pledge to act and interact in ways that contribute to an open, welcoming, diverse, inclusive, and healthy community.

2024-10-03 05:00 UTC, whyvineet approved these changes

2024-10-03 05:01 UTC, merged