Add Contributor Section
c0sm0void/ReVot pull request #27
Opened 2024-10-05 16:58 UTC by souvikpramanikgit

I added the contributor section.

2024-10-05 17:10 UTC, souvikpramanikgit commented
Fix #21

2024-10-05 19:25 UTC, c0sm0void commented
@souvikpramanikgit please resolve the conflicts and do a few more updates as per your issue, like animations and layout fixes. Someone else has already done the contributor view.

2024-10-06 04:51 UTC, whyvineet requested changes
I noticed a few areas where the README could be improved for clarity and consistency. These changes would help to ensure that the README is easy for potential contributors to understand and follow. Thank you for your work on this project!

2024-10-06 04:51 UTC, whyvineet commented on README.md
>  This project is licensed under the [MIT License](https://opensource.org/licenses/MIT).
This paragraph is showing with H2 text font

2024-10-06 04:51 UTC, whyvineet commented on README.md
>    <a href="https://github.com/c0sm0void/ReVot">
Explain this as this is showing as it is in the bottom

2024-10-06 19:44 UTC, c0sm0void approved these changes

2024-10-06 19:45 UTC, merged